### ISSUE TITLE
line-spacing is not restored

### ISSUE THREAD

**Issue by protesilaos** [minad/org-modern#1]
Hello Daniel.  Congratulations for doing this and thanks for sharing!

Basically what the title says: `org-modern-mode` does not restore the `line-spacing` after it is disabled.

**Comment by minad** [comment]
I fixed the issue. If you have suggestions on how the styling or the face definitions can be improved please let me know. Probably some elements could use better contrast. I used neutral coloring which works well with Modus and also some other themes I've tried.

**Comment by protesilaos** [comment]
> I've got inspired by our completion theming discussion to also
> experiment a bit with styling.

In turn, I realised after seeing your demo here that I was meaning to
simplify the `org-checkbox` face because it did not fit in with the
other styles:
<https://github.com/protesilaos/modus-themes/commit/fa6a81ac91cd95b53869942378eb0083c839b0e4>.

> I had planned to restore this, but then I forgot about it. 

No worries!

> Originally I hadn't the intention to overwrite the line spacing, but I
> am afraid it is necessary to do this to align the boxes.

I haven't tested this, but what would happen if instead of a negative
`org-modern-line-spacing` box you had a positive one with its `:color`
being that of the main background?  Something like this (does not work
on its own as it messes up mouse hover effects and whatnot):

```elisp
(defface org-modern-label
  `((t :height 0.75
       :inherit variable-pitch
       :width condensed :weight regular
       :underline nil
       :box (:line-width 7 :color "white")))
  "Parent face for labels.")
```

I guess you tried that and it did not work.  Just saying...

> I fixed the issue. If you have suggestions on how the styling or the
> face definitions can be improved please let me know.

I will keep using it and inform you accordingly.

> Probably some elements could use better contrast.

They look good to me even without any further tweaks.

I think only the inactive time/date could be tweaked a bit.  The active
ones could be adjusted accordingly.  For example:

```elisp
(defface org-modern-time-active
  '((default :inherit org-modern-label :weight semibold)
    (((background light))
     :background "gray35" :foreground "white")
    (t :background "gray75" :foreground "black"))
  "Face used for active time labels.")

(defface org-modern-time-inactive
  '((default :inherit org-modern-label :background "gray50")
    (((background light))
     :foreground "gray95")
    (t :foreground "gray5"))
  "Face used for inactive time labels.")

(defface org-modern-date-inactive
  '((default :inherit org-modern-label)
    (((background light))
     :background "gray90" :foreground "gray30")
    (t :background "gray20" :foreground "gray70"))
  "Face used for inactive date labels.")
```

[ Notice the `default` spec, which is passed to all the rest. ]

> I used neutral coloring which works well with Modus and also some
> other themes I've tried.

Those work well also because of the "button" aesthetic.  The "DONE", for
example, does not need to be green on top of already standing out.  I
like them!

**Comment by minad** [comment]
> I guess you tried that and it did not work. Just saying...

I tried both negative and positive borders. Only negative borders seem to work well. Note that I already set the border color to the background. I must admit I do this in an unorthodox way in `org-modern-mode`:

~~~ elisp
    (when-let (width (plist-get (face-attribute 'org-modern-label :box) :line-width))
      (set-face-attribute
       'org-modern-label nil
       :box `(:color ,(face-attribute 'default :background nil t) :line-width ,width)))
~~~

**Comment by minad** [comment]
> Those work well also because of the "button" aesthetic. The "DONE", for
example, does not need to be green on top of already standing out. I
like them!

Yes, exactly. The idea is from Nicolas Rougier in his svg-tag-mode package. Generally I find that some of his style ideas transfer over well to your Modus themes and look good there. For example setting a window divider to get some breathing space and also the buttons. You probably noticed that I preserved the TODO color from the theme via inverse-video.

**Comment by protesilaos** [comment]
[ I fetched the latest changes.  Things are look great!  Will report an
  issue separately. ]

> > Those work well also because of the "button" aesthetic. The "DONE",
> > for example, does not need to be green on top of already standing
> > out. I like them!

> Yes, exactly. The idea is from Nicolas Rougier in his svg-tag-mode
> package. Generally I find that some of his style ideas transfer over
> well to your Modus themes and look good there. For example setting a
> window divider to get some breathing space and also the buttons. You
> probably noticed that I preserved the TODO color from the theme via
> inverse-video.

I think Nicolas' stylistic choices are very promising.  We need more of
that work to upgrade our interfaces---we do use them everyday!

Yes, they fit in nicely with the colours of the modus-themes.  Though I
feel even a simplified palette with some more contrast of, say, a
minimum 4.5:1 would still do the trick.

**Comment by minad** [comment]
(Note that I removed the line-spacing overwrite in a separate commit, such that org-modern stays more out of the way.)

> Yes, they fit in nicely with the colours of the modus-themes. Though I
feel even a simplified palette with some more contrast of, say, a
minimum 4.5:1 would still do the trick.

While I agree with the general sentiment of reducing overloaded and cluttered interfaces, adding too much color etc, there are decisions I disagree with. For example I don't like at all that Elegant/Nano Emacs use such a long contrast. Interfaces should be designed with accessibility in mind also for visually impaired people. Your themes are excellent with that respect. Furthermore I feel that we lose something by overly reducing the set of available colors to only a handful of semantic colors. I also like your approach here to strive for consistency across packages and modes, which gives us also a semantic feeling without the severe restrictions of a too small set of colors. 

In org-modern I try to avoid introducing heavy elements, staying with text only. While I like the style of Nicolas' work, I am personally not fond of using images. I am also not a user of icons. So this is maybe a minor technical criticism. Using text has also advantages since one can move over the text elements with the cursor. I recently improved that for dates, todo keywords and tags, see #2. Therefore I rather restrict myself to the simpler, less flexible text elements, even if it means that I lose some eye candy. However I think that one could rather easily improve the display engine to provide more stylistic options: Better borders, rounded corners, text baseline adjustments, ... These are all simple modifications which could help creating "modern" looking interfaces with simple means.
