### ISSUE TITLE
Incompatibility between code block and display-line-numbers-mode

### ISSUE THREAD

**Issue by ST-Saint** [minad/org-modern#114]
<img width="345" alt="org-modern" src="https://user-images.githubusercontent.com/13213464/218347102-2460f832-c752-438c-9ad4-a526af0ee7c6.png">

Could the border be rendered on the right side of the line number?

**Comment by minad** [comment]
No, afaik this is not possible since the fringe position and the line number positions are fixed by the Emacs display engine. Unfortunately we cannot change/configure that from Elisp. It still doesn't look too bad to me. I think one should only enable display-line-numbers-mode temporarily anyway. See for example consult-goto-line, which enables the line numbers only during the jump.
