### ISSUE TITLE
keep point position during line navigation

### ISSUE THREAD

**Issue by kimim** [minad/org-modern#134]
When `org-modern` is enabled, after `C-a` and then `C-p/C-n` cannot keep point in the beginning of each line.

**Comment by minad** [comment]
I cannot reproduce this without a minimal recipe based on emacs -Q. This is likely not an Org-modern issue anyway, since Org-modern only performs fontification. You may want to set `org-modern-hide-stars=nil` if you prefer to see the point location inside the stars.

**Comment by kimim** [comment]
Thanks for fast feedback. Setting `org-modern-star` to `nil` solve my issue.

**Comment by kimim** [comment]
It happens when all the heading are folded, `C-a` to beginning of the heading, when navigating lines, the cursor will locate to end of `...`.

**Comment by minad** [comment]
You can also set `org-speed-commands=t` and use `n` and `p` on the stars to move around. This doesn't seem to lead to the issue.

**Comment by kimim** [comment]
I use this config:
```emacs-lisp
(package-initialize)
(use-package org-modern
  :custom
  (org-modern-star '("⦿" "○" "●" "◌" "⯈"))
  (org-modern-list
   '((?- . "▬")
     (?+ . "♦")
     (?* . "●")))
  (org-modern-checkbox
   '((?X . "☑")
     (?- . #("☐–" 0 2 (composition ((2)))))
     (?\s . "☐")))
  (org-modern-timestamp nil)
  (org-modern-tag nil)
  (org-modern-todo nil)
  (org-modern-block-name nil)
  (org-modern-block-fringe nil)
  (org-modern-keyword nil)
  :hook
  (org-mode . (lambda ()
                "Beautify Org Symbols"
                (push '(":category:" . ":▲:") prettify-symbols-alist)
                (push '("#+begin_src" . "«" ) prettify-symbols-alist)
                (push '("#+end_src" . "»" ) prettify-symbols-alist)
                (prettify-symbols-mode)
                (org-modern-mode))))
```

and this org file

```orgmode
* Hello
** hi

* Test
** hello
* hello1
** hello again
```

When all second level heading ** are hided, `C-a` to beginning of `hello1`, and `C-p`, the cursor will move to end of ... of `Test`.

**Comment by kimim** [comment]
It looks like this:
![emacs_egGLTPeRaK](https://github.com/minad/org-modern/assets/5523431/4fb74c9b-57a7-4b47-a5f0-9026a9cf55dc)

**Comment by minad** [comment]
Sure, I see the issue. It is wontfix.

**Comment by minad** [comment]
To me this looks like some weird movement bug - triggered by Org-modern, but not fixable here, since the normal movement commands are affected. I use the following file:

~~~
* First
** Sub
* Second
~~~

After folding it looks like this:

~~~
* First...
* Second
~~~

I can move `<up>` and `<down>` without issues, after I have placed the cursor at the beginning with `M-<`:

~~~
|* First...
* Second
~~~

However as soon as I move the cursor behind the ..., up and down movement gets messed up. It seems as if the old position is somehow remembered.

~~~
* First...|
* Second
~~~

**Comment by minad** [comment]
> I guess the face of leading star is set to 'display, and when headings are folded, the leading star of sub-heading is still visible or displayable, then the cursor will move to that visible star, unfortunately, it is just at the end of ...

Yes, somehow. But this is non-sensical nevertheless, since the whole content section is invisible and should not affect movement. Also note what I wrote above - the behavior of `previous-line` depends on the old locations of point before. Maybe this is caused by fontification updating the display property depending on point movement.

**Comment by kimim** [comment]
```
* A1
** A11
*** A113
|** A12
* B1
** B11
```
If level 2 heading A11 is folded, `|` can move to beginning of `** A11`, `*** A113` wont effect.

**Comment by minad** [comment]
No, you cannot always.

1. Fold and move to the end.

~~~
* A1
** A11...|
** A12
* B1
** B11
~~~

2. Move before A12.

~~~
* A1
** A11...
|** A12
* B1
** B11
~~~

3. Move up.

~~~
* A1
** A11...|
** A12
* B1
** B11
~~~

This is the non-deterministic behavior I meant before.

**Comment by kimim** [comment]
Now, either continue to use pretty star replacement, or accept plain `*`. Thanks.

**Comment by minad** [comment]
> Now, either continue to use pretty star replacement, or accept plain *.

Or report the problem upstream, such that the handling of `display` properties could be improved in Emacs. But this likely needs a minimal recipe without Org and without Org-modern.

**Comment by rhstanton** [comment]
Here's  a workaround, created with the assistance of Claude Code, that (for me) keeps both the star prettification **and** line-move-visual. It works for me, but I haven't tested it deeply — I'm posting in the hope it's useful to others who hit this. Corrections welcome.

As @minad noted, this isn't really org-modern's bug: line-move-visual recomputes its goal column from posn-at-point, and when column 0 carries a display property (the prettified star) the reported x seems to be bogus (the cursor is drawn after the display), so the goal column becomes huge and C-n/C-p land at the end of the neighbouring line.

The idea is simple: **when a vertical move starts at the logical beginning of a line, the goal column should just be 0.** So force it — and only when line-move-visual would otherwise recompute (mirroring its own keep-vs-recompute test), so continuation moves and goal-column tracking past short/empty lines are left untouched:
```
  (defun my/line-move-visual-bol-goal (orig arg &optional noerror)
    "Force the visual goal column to 0 when a vertical move starts at logical BOL.
  `line-move-visual' otherwise recomputes the goal from `posn-at-point', whose x is
  bogus at a column-0 `display' property (e.g. an org-modern heading star), sending
  point to the end of the neighbouring line."
    (if (and (bolp)
             (not goal-column)               ; respect an explicit C-x C-n goal
             ;; only step in when line-move-visual WOULD recompute the goal;
             ;; on a continuation move the goal is being carried -- leave it.
             (not (and (consp temporary-goal-column)
                       (memq last-command (list 'next-line 'previous-line this-command)))))
        (progn
          ;; (cons 0.0 hscroll) is exactly what line-move-visual computes at a real
          ;; column 0, so display-line-numbers and hscroll should come out right.
          (setq temporary-goal-column (cons 0.0 (window-hscroll)))
          (let ((last-command 'previous-line))  ; make it KEEP this goal, not recompute
            (funcall orig arg noerror)))
      (funcall orig arg noerror)))

  (advice-add 'line-move-visual :around #'my/line-move-visual-bol-goal)
```

In my setup the result is: org-modern-hide-stars 'leading + fold bullets stay, line-move-visual stays, and C-a then C-p/C-n on a heading keeps point at column 0. It also doesn't seem to interfere with correct cursor movement in other situations.
