### ISSUE TITLE
TODO labels backgound does not work well with line-spacing 0.4 

### ISSUE THREAD

**Issue by merrickluo** [minad/org-modern#147]
Hi, thanks for the pretty package. 

I see the README mentioned it should work fine with line-spacing from 0.1 to 0.4? the font is JetBrains Mono, I'm using doom emacs and disabled org +pretty.

![image](https://github.com/minad/org-modern/assets/1495875/973b4873-b5e7-4569-9036-dea24074bbbd)

**Comment by minad** [comment]
Thanks. Obviously 0.4 is too large for your specific combination of fonts. See also the duplicate issue #66. 

There is not much we can do, except choosing your fonts and settings more carefully.

One alternative would be to try to use the `raise` display property as mentioned in #140 to achieve better alignment of TODO/IDEA within the label. But then, tuning labels individually based on the font sizes will be costly. In #144 I had a long discussion with the Org maintainer Ihor about the redisplay cost due to org-modern. The more properties we add the more costly org-modern will be for the redisplay engine.

**Comment by merrickluo** [comment]
Thanks for the explanation :pray: , I guess my best option is still patching the font.
