### ISSUE TITLE
Table formatting is shifted when the table contains a divider line.

### ISSUE THREAD

**Issue by mok0** [minad/org-modern#155]
Like the subject line says: table formatting is shifted when the table contains a divider line. I enclose a screen dump of how it looks in my Emacs. I am running under macOS Ventura 13.6 (22G120), and I have compiled Emacs v. 29.1 using the build script` jimeh/build-emacs-for-macos.git` here on github.

![Screenshot 2023-10-28 at 11 33 36](https://github.com/minad/org-modern/assets/878168/d4f1a97f-541c-4118-bf76-31cf8c6be1c0)

**Comment by minad** [comment]
This is likely a font problem caused by variable pitch fonts. We would need pixel alignment to fix this. If this is not the case, please provide a minimal example based on emacs -Q with only org-modern loaded.

**Comment by mok0** [comment]
When I launch a mininal Emacs with only org-moderne loaded and using the default font that comes with Emacs, the problem does not appear, the table looks fine. So you are right, it must be the variable pitch fonts creating this. I guess the goto solution is to not use divider lines in tables. Thanks for your quick reply!

**Comment by CVanmarcke** [comment]
I had the same problem, caused by variable pitch (I use `mixed-pitch` to set this automatically). The problem persisted even if the `org-table` face had a fixed pitch. To fix it I had to add the following to my org-modern configuration:

```
(setq org-modern--table-sp '((space :width 1)
                             (space :width 1)))
```

The divider line however is still the same height as the rest of the text (instead of a thin horizontal line), but I don't mind too much.

**Comment by oantolin** [comment]
Wow, @CVanmarcke, that is magic! I will add it to my configuration without attempting to understand what the issue was.
