### ISSUE TITLE
cannot change timestamps after creation

### ISSUE THREAD

**Issue by japhir** [minad/org-modern#2]
The nicely rendered date+timestamp blocks now act as a single character that the cursor jumps over, so I can no longer shift + up arrow to increment the hours/minutes/day anymore. Is there a way to still allow this while rendering it nicely? Or otherwise disable the fancy rendering temporarily when point is on it, like what [org-appear](https://github.com/awth13/org-appear) does?

**Comment by minad** [comment]
Thank you for the report! I changed the styling method such that I avoid display properties in this case. This ensures that the time stamps stay editable. I try to avoid the org appear approach here for now since it is more dynamic and requires more complex facilities. But I may add something like org-appear functionality here in the future, or even better we could try to make our package compatible with org-appear. Personally I haven't tried org-appear yet.

**Comment by minad** [comment]
I also improved it for some of the other elements, such that they stay editable.
