### ISSUE TITLE
Some stylistic tweaks

### ISSUE THREAD

**Issue by protesilaos** [minad/org-modern#21]
Good day Daniel!

Some ideas for this package after a few days of using it with its
current defaults:

* Make `variable-pitch` optional.
* Apply a bespoke face to priorities (even if you keep it empty).  I would
  personally add a faint warm background to contrast both with the TODO
  and the tags.
* The default values for `org-modern-priority` do not work well with all
  fonts.  In my config I switched them to Greek letters.  The extra face
  would allow me to visualise them as "buttons" like the other elements.

**Comment by minad** [comment]
> Make variable-pitch optional.

I've considered adding an option to this, but there is almost no benefit of doing that since you can do `(set-face-attribute 'org-modern-label nil :inherit nil)`. The advantage of a variable is that you can set it before loading the package. What do you think?

> Apply a bespoke face to priorities

Yes, the priority styling is problematic. I am probably going to change this, using a label style as you propose. See also #12.

**Comment by protesilaos** [comment]
> > Make variable-pitch optional.
> 
> I've considered adding an option to this, but there is almost no benefit of doing that since you can do `(set-face-attribute 'org-modern-label nil :inherit nil)`. The advantage of a variable is that you can set it before loading the package. What do you think?

It is not a pressing issue either way: I am happy with whatever you prefer.  The variable adds more complexity.

I just thought that the `variable-pitch` does not add to the "button-ness" (or "label-ness") that the background and padding create.  Though that perception will depend on the exact fonts.

> > Apply a bespoke face to priorities
> 
> Yes, the priority styling is problematic. I am probably going to change this, using a label style as you propose. See also #12.

Thanks!

**Comment by minad** [comment]
Hey Prot, please let me know if the adjustments work for you as expected (priority style, variable pitch, default font size). Thanks!

**Comment by protesilaos** [comment]
Thank you!  All good.

I now see the problem you mentioned with the vertically compressed
labels after increasing their height.  It is due to the
`org-modern-label-border`.  Check these:

![2022-03-06_15:02:26_576x576](https://user-images.githubusercontent.com/12828033/156924493-05ce9f88-b6c4-413a-babb-26c34257cdf0.png)

![2022-03-06_15:03:14_576x576](https://user-images.githubusercontent.com/12828033/156924496-5a72b8c2-5241-4764-9a08-7374e7cd461a.png)

![2022-03-06_15:03:17_576x576](https://user-images.githubusercontent.com/12828033/156924497-bf31b117-1d41-4e25-abd4-176ffe369dc7.png)

![2022-03-06_15:04:03_576x576](https://user-images.githubusercontent.com/12828033/156924498-e0c1f583-e614-492f-8ce5-29c6e2c01d8b.png)

![2022-03-06_15:04:08_576x576](https://user-images.githubusercontent.com/12828033/156924499-dcf96694-ac5f-4190-856d-cbf8ac65fab9.png)

[ By the way, switching between light and dark reveals the
  `org-modern-label-border` because its colour is determined when the
  mode gets enabled. ]

**Comment by minad** [comment]
> I now see the problem you mentioned with the vertically compressed
labels after increasing their height. It is due to the
org-modern-label-border. Check these:

Yes, this is exactly what I mean. The user can alleviate the issue by adjusting the org-modern-label-border option.

> [ By the way, switching between light and dark reveals the
org-modern-label-border because its colour is determined when the
mode gets enabled. ]

Yes, I am aware of that. I could catch theme switches, but I don't think this is worth it since it is a rare scenario. It suffices to switch org-modern-mode off and on again to reset.

**Comment by protesilaos** [comment]
> Yes, I am aware of that. I could catch theme switches, but I don't think this is worth it since it is a rare scenario. It suffices to switch org-modern-mode off and on again to reset.

Agreed!

**Comment by protesilaos** [comment]
Great!
