### ISSUE TITLE
FEATURE REQUEST: Add overlay icons for SCHEDULED: and DEADLINE: ?

### ISSUE THREAD

**Issue by duckwork** [minad/org-modern#42]
Turning `SCHEDULED:`, `DEADLINE:`, and `CLOSED:` into icons would be pretty nice. Possible also drawer titles?

**Comment by minad** [comment]
I think you can do that trivially with prettify-symbols-mode. See tecosaurs config which does that heavily. I could add a org-modern-prettify-alist to org-modern but it is kind of pointless. No need to overlap with prettify-symbols-mode. The idea of org-modern is generally to keep the content editable, therefore I avoid icons. Furthermore org-modern only styles elements which would be hard to style otherwise, since they require parsing. It tries to go beyond what prettify-symbols-mode allows you to do.

**Comment by duckwork** [comment]
I  didn't even think of prettify-symbols-mode; this helps a lot, thanks!
