### ISSUE TITLE
keep spaces before code block first and last line with "#+"

### ISSUE THREAD

**Issue by K-gihu** [minad/org-modern#48]
Hi, thanks for this package. I have been using this for quite a well and it proved stable and beautiful.
However, when inserting source block below a plain list item, I noticed that the spaces before the displayed "src" are made invisible.
In my opinion, spaces should be kept to maintain indentation consistency.

**To reproduce**
```text
- item
  #+begin_src python
    print("hello")
  #+end_src
```

Put this in an org file and activate org-modern-mode to see that spaces before #+ disappear and space before the code stays.

**Comment by minad** [comment]
The problem is also that the source block formatting draws the vertical line inside the fringe. Therefore I argue that org-modern generally doesn't work well with indented code blocks or indented headlines. If you want to use indentation, I would recommend to set `org-modern-block=nil` and disable org table styling.
