### ISSUE TITLE
Recommended line-spacing value of 0.3 also applies to fixed-pitch and seems off

### ISSUE THREAD

**Issue by ParetoOptimalDev** [minad/org-modern#66]
Do other org-modern users typically just `(setq-default line-spacing 0.3)` and remain relatively unbothered by the extra heigh it adds to code blocks?

line-spacing nil:

![2022-06-12_13-46-line-spacing-nil](https://user-images.githubusercontent.com/93023868/173248715-0db00012-41cf-4c79-ad9e-0985d96999e8.png)

line-spacing 0.3:

![2022-06-12_13-45-0 3-linespacing](https://user-images.githubusercontent.com/93023868/173248722-45781bf2-874b-4df7-8076-293272ddcd07.png)

I like a little extra line spacing between variable pitch fonts, but having it in fixed-pitch fonts just feels wrong. Is there a way to set line-spacing differently for fixed and variable pitched fonts?

**Comment by ParetoOptimalDev** [comment]
This might be related to my fonts:

https://emacs.stackexchange.com/questions/10516/excessive-line-spacing-with-certain-fonts

**Comment by minad** [comment]
I don't know. Iirc there is a possibility to set line spacing per face. But the last time I tried this I wasn't successful. If you figure out a solution I would be interested in hearing it. But I am also not bothered much by this. Using a single spacing is acceptable if you use fonts which have the same height and fit well together.

**Comment by ParetoOptimalDev** [comment]
Thanks for the quick response. I'll investigate other fonts since I'm not 100% happy with the ones I have anyway.

**Comment by minad** [comment]
> This might be related to my fonts:
> 
> https://emacs.stackexchange.com/questions/10516/excessive-line-spacing-with-certain-fonts

Yes, spacing is highly dependent on your font. You could even decide to use no spacing at all if your font is low. For fonts with a large height, a larger spacing may be desirable to give the text some breathing room.

**Comment by minad** [comment]
> Thanks for the quick response. I'll investigate other fonts since I'm not 100% happy with the ones I have anyway.

I am also switching the font from time to time. Currently I use Iosevka, which offers multiple variants and seems flexible and hackable. See also @protesilaos' Iosevka Comfy. Before that I tried Hack, which has a relatively large height (too large for me). Before Hack, I used Source Code Pro or its Hasklig variant for a longer time.

**Comment by protesilaos** [comment]
Yay for Iosevka!  It does things right and if you do not like some
stylistic choices you can produce your own variant.

I can't remember all the details right now, but Roboto Mono never quite
worked for me.  Looking at your first screenshot, I recall it had
awkward line spacing and required a particular `:height` to look decent.
Specifically, the character is not centred in the box of the glyph but
is instead tilted downwards.  You can observe this by placing the cursor
next to a parenthesis (disable `show-paren-mode` if it helps with the
comparison).

This is not specific to Roboto Mono.  For example, the otherwise good
looking Source Code Pro has the same problem at certain point sizes.
Look at this () at face height 120.  Compare it to Iosevka where
everything looks verticall balanced at all heights (my custom build of
Iosevka is not relevant in this regard---the default is excellent).

![2022-06-13_06:02:24_800x244](https://user-images.githubusercontent.com/12828033/173272061-0ac81154-3431-4402-a559-28374139632c.png)

![2022-06-13_06:02:42_800x244](https://user-images.githubusercontent.com/12828033/173272063-0ce998ce-7b68-4889-b8d7-5ca5446e8b35.png)

Oh, there is a typo there...  Too lazy for other screenshots.

**Comment by ParetoOptimalDev** [comment]
Thanks @minad and @protesilaos!

Wow, I didn't know that fonts could look so much worse because of this issue. The example you show with Iosevka is quite large.

How do other applications avoid this... I don't think this issue exists on vs code for example. To be sure I'd have to test it though.
